#!/bin/bash
help () {
  echo
  echo "Usage: mkfw-ip ip ratelimit connlimit "
  echo "Example: mkfw-ip 172.16.100.11 100 50000"
  echo "Rate limit: limit the number of new connections per second for DoS prevention.  Default is 20/second"
  echo "Limit total number of established connections.  Prevent firewall from running out of memory in a DoS"
  echo
  exit
}


PIP=$1
CHAIN_ETH_IN="INBOUND"
CHAIN_ETH_OUT="OUTBOUND"
CHAIN_IP_IN="INBOUND-$PIP"
CHAIN_IP_OUT="OUTBOUND-$PIP"
RATELIMIT=$2
CONNLIMIT=$3

NARGS=$(echo $@ | wc -w)
if [ $NARGS -ne 3 ]; then
        echo "Incorrect number of arguments"
        help
fi


#######################################
#
# Create IP Chain
# OUT Default: ESTABLISHED,RELATED,ICMP-ECHO
# IN Default: ESTABLISHED,RELATED,ICMP-ECHO
#
###################################
iptables -L $CHAIN_IP_IN > /dev/null 2>&1
if [ $? -eq 0 ]; then
        echo "WARNING: $CHAIN_IP_IN already exists"
else
	iptables -N $CHAIN_IP_IN
	iptables -A $CHAIN_IP_IN -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -A $CHAIN_IP_IN -m state --state INVALID -j DROPnLOG
  iptables -A $CHAIN_IP_IN -m connlimit --connlimit-daddr --connlimit-mask 32 --connlimit-above $CONNLIMIT -m comment --comment "connlimit" -j DROPnLOG
  iptables -A $CHAIN_IP_IN -m hashlimit --hashlimit-above $RATELIMIT --hashlimit-name $CHAIN_IP_IN -m comment --comment "ratelimit" -j DROPnLOG
	iptables -A $CHAIN_IP_IN -p icmp --icmp-type echo-request -m limit --limit 20s -j ACCEPT
	iptables -A $CHAIN_IP_IN -j INBOUND-DEFAULT
fi

iptables -L $CHAIN_IP_OUT > /dev/null 2>&1
if [ $? -eq 0 ]; then
        echo "WARNING: $CHAIN_IP_OUT already exists"
else
  iptables -N $CHAIN_IP_OUT
  iptables -A $CHAIN_IP_OUT -m hashlimit --hashlimit-above 15mb/s --hashlimit-mode srcip --hashlimit-burst 30mb --hashlimit-name $CHAIN_IP_OUT -j DROPnLOG
	iptables -A $CHAIN_IP_OUT -m state --state RELATED,ESTABLISHED  -j ACCEPT
	iptables -A $CHAIN_IP_OUT -m state --state INVALID -j DROPnLOG
  iptables -A $CHAIN_IP_OUT -m connlimit --connlimit-daddr --connlimit-mask 32 --connlimit-above $CONNLIMIT -m comment --comment "connlimit" -j DROPnLOG
  iptables -A $CHAIN_IP_OUT -p icmp --icmp-type echo-request -j ACCEPT
	iptables -A $CHAIN_IP_OUT -j OUTBOUND-DEFAULT
fi
iptables -t mangle -L $CHAIN_IP_OUT > /dev/null 2>&1
if [ $? -eq 0 ]; then
	echo "WARNING: mangle chain $CHAIN_IP_OUT already exists"
else
	iptables -N $CHAIN_IP_OUT -t mangle
fi

###################################
#
# Rules in ETH Chain
# jump to IP Chain
#
###################################
iptables -L $CHAIN_ETH_IN -n | grep -q "^$CHAIN_IP_IN "
if [ $? -eq 0 ]; then
        echo "WARNING: RULE $CHAIN_IP_IN already exists"
else
        iptables -I $CHAIN_ETH_IN -d $1 -j $CHAIN_IP_IN
fi
iptables -L $CHAIN_ETH_OUT -n | grep -q "^$CHAIN_IP_OUT "
if [ $? -eq 0 ]; then
        echo "WARNING: RULE $CHAIN_IP_OUT already exists"
else
        iptables -I $CHAIN_ETH_OUT -s $1 -j $CHAIN_IP_OUT
fi
# Mangle Table
iptables -t mangle -L OUTBOUND -n | grep -q "^$CHAIN_IP_OUT "
if [ $? -eq 0 ]; then
        echo "WARNING: RULE $CHAIN_IP_OUT already exists"
else
        iptables -t mangle -I OUTBOUND -s $1 -j $CHAIN_IP_OUT
        iptables -t mangle -I $CHAIN_IP_OUT -j ACCEPT 
fi
