#!/bin/bash
CHAIN_NAME="FORWARD"
SYSCONFIG="/etc/sysconfig/network-scripts"


usage () {
        echo
        echo "Usage: mkfw-intf 'IN/OUT/MGMT/TRADING/WAN' 'interface' 'ip address' 'gateway'"
        echo "Examples: "
        echo "          > mkfw-intf in eth0 10.1.2.10/24 10.1.2.1"
        echo
}


if [ $# -ne 4 ]; then
	echo "Incorrect number of arguments"
	echo
	usage
	exit
fi



DIRECTION=$(echo $1 |tr [:lower:] [:upper:])
INT=$(echo $2 |tr [:upper:] [:lower:])
NETWORK=$(ipcalc -n $3 | awk -F "=" '{print $2}')
PREFIX=$(ipcalc -p $3 | awk -F "=" '{print $2}')
GATEWAY=$(echo $NETWORK | awk -F "." '{printf "%s.%s.%s.1" $1 $2 $3}')

if [ $DIRECTION != "IN" -a $DIRECTION != "OUT" -a $DIRECTION != "MGMT" -a $DIRECTION != "TRADING" -a $DIRECTION != "WAN" ]; then
	echo "Incorrect first arguement"
	usage
	exit
fi


# Delete Any Previous Rules For Interface
LINE=$(iptables -L $CHAIN_NAME -nv --line-numbers |awk "\$8 ~ /^$2\$/ {print \$1}")
if [ "x$LINE" != "x" ]; then
	iptables -D $CHAIN_NAME $LINE
fi

# Bring up interface on boot
cat > $SYSCONFIG/ifcfg-$INT <<-ENDCAT
TYPE=Ethernet
BOOTPROTO=none
DEVICE=$INT
ONBOOT=yes
ETHTOOL_OPTS=" -G $INT rx 4096; -G $INT tx 4096"
ENDCAT



forwarding=0
# Insert iptables rule
if [ $DIRECTION != "MGMT" ]; then
  if [ $DIRECTION == "TRADING" -o $DIRECTION == "WAN"]
  then
    DIRECTION=OUT
    TABLE=$(echo $DIRECTION |tr [:upper:] [:lower:])
    echo "ip route 0.0.0.0/0 via $GATEWAY table $TABLE" >> $SYSCONFIG/route-$INT
  fi

	iptables -I $CHAIN_NAME -o $2 -j ${DIRECTION}BOUND
	forwarding=1


  if [ $DIRECTION == "IN" ]; then
    iptables -t mangle -I PREROUTING -i $2 -j OUTBOUND
    echo "pref 80 iif lo to $NETWORK/$PREFIX lookup main" >> $SYSCONFIG/rule-$INT
  fi
else
  LINE=$(iptables -L INPUT -nv --line-numbers | tail -1 | awk '{print $1}')
  iptables -I INPUT $LINE -i $2 -j ACCEPT

  echo "pref 50 fwmark 101 lookup wan" >> $SYSCONFIG/rule-$INT
  echo "pref 51 fwmark 102 lookup trading" >> $SYSCONFIG/rule-$INT
  echo "pref 80 iif lo to $NETWORK/$PREFIX lookup main" >> $SYSCONFIG/rule-$INT
  echo "pref 100 iif lo to 10.0.0.0/8 lookup mgmt" >> $SYSCONFIG/rule-$INT
  echo "pref 100 iif lo to 192.168.0.0/16 lookup mgmt" >> $SYSCONFIG/rule-$INT
  echo "pref 100 iif lo to 172.16.0.0/12 lookup mgmt" >> $SYSCONFIG/rule-$INT
  echo "0.0.0.0/0 via $GATEWAY table mgmt " > $SYSCONFIG/route-$INT



fi


#set sysctl variable for forwarding or not.
cat > /etc/sysctl.d/$INT.conf <<END
net.ipv4.conf.$INT.forwarding = $forwarding
net.ipv4.conf.$INT.rp_filter = 0
END

sysctl -w net.ipv4.conf.$INT.forwarding=$forwarding
sysctl -w net.ipv4.conf.$INT.rp_filter=0


## SET IP Address
vtysh -c "conf term" -c "int $2" -c "ip address $3" -c "end" -c "copy run start"

service iptables save
