#!/bin/bash

LOGFILE=/var/log/fwchangelog 
COMMAND=rmlvs-service
log() {
   message="$@"
   echo "$(date +%c) $COMMAND $message">>$LOGFILE
   logger -t $COMMAND "$message"
}

NARGS=$(echo $@ | wc -w)
if [ $NARGS -le 1 ]; then
   echo "Insufficient Arguments"
   echo
   echo "Usage: rmlvs-service (tcp|udp) 'Virtual IP/Netmask:Port'"
   echo "Example: rmlvs-service tcp 192.168.0.1/24:80"
   echo
   exit
fi

LOIP=$(echo $2| cut -d ":" -f 1)
IP=$(echo $2| cut -d ":" -f 1 |cut -d "/" -f 1)
NETMASK=$(echo $2| cut -d ":" -f 1| cut -d "/" -f 2)
PORT=$(echo $2| cut -d ":" -f 2)

if [ "x$1" != "xtcp" -a "x$1" != "xudp" ]; then
   echo "Arg1: tcp or udp ($1)"
   echo
   echo "Usage: rmlvs-service (tcp|udp) 'Virtual IP/Netmask:Port'"
   echo "Example: rmlvs-service tcp 192.168.0.1/24:80"
   echo
   exit
fi

if [ $1 = "tcp" ]; then
   PROTO="-t"
elif [ $1 = "udp" ]; then
   PROTO="-u" 
else
   exit
fi

ipvsadm -L -n $PROTO $IP:$PORT > /dev/null 2>&1
if [ $? -ne 0 ]; then

   echo "WARNING: The Virtual Service $IP:$PORT does not exist"
   exit
else
   ipvsadm -D $PROTO $IP:$PORT 
   log ipvsadm -D $PROTO $IP:$PORT 
fi

iptables -L INPUT -nv | grep $IP| grep $PORT > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "WARNING: There is no INPUT table rule to delete for $IP"
   exit
else
   LNUM=$(iptables -L INPUT -nv --line-numbers|grep $IP|grep $PORT|awk '{print $1}')
   iptables -D INPUT $LNUM
   log iptables -D INPUT $LNUM
vtysh << EEND 
conf term
interface lo
no ip address $LOIP
end
copy run start
exit
EEND
log "Remove $LOIP from loopback interface in quagga"

fi


exit
